// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {cinema} from '../models';
import {settingsops} from '../models';
import {mcp} from '../models';
import {skill} from '../models';
import {git} from '../models';
import {lsp} from '../models';
import {automation} from '../models';
import {browser} from '../models';
import {calendar} from '../models';
import {connector} from '../models';
import {main} from '../models';
import {provider} from '../models';
import {llm} from '../models';
import {context} from '../models';
import {agent} from '../models';

export function AcceptChanges(arg1:string,arg2:Array<string>):Promise<void>;

export function AddProject(arg1:string):Promise<store.Project>;

export function AddSitePermission(arg1:string,arg2:string):Promise<Array<store.BrowserSitePermission>>;

export function ArchiveSession(arg1:string):Promise<void>;

export function BrowserEvaluate(arg1:string):Promise<string>;

export function BrowserNavigate(arg1:string):Promise<string>;

export function BrowserScreenshot():Promise<string>;

export function BrowserSnapshot():Promise<string>;

export function BrowserVersion():Promise<Record<string, any>>;

export function CancelCinemaJob(arg1:string):Promise<void>;

export function CheckDependencies():Promise<Array<store.DependencyCheckResult>>;

export function ClearBrowserData():Promise<void>;

export function CloseShell(arg1:string):Promise<void>;

export function CommentOnHunk(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CompactSession(arg1:string):Promise<store.Session>;

export function CreateCustomPet():Promise<Array<store.Pet>>;

export function CreateSnapshot(arg1:string,arg2:string):Promise<store.SnapshotEntry>;

export function DeleteArchivedSession(arg1:string):Promise<void>;

export function DeleteArchivedSessions():Promise<void>;

export function DeleteAutomation(arg1:string):Promise<void>;

export function DeleteCalendarEvent(arg1:string):Promise<void>;

export function DeleteCinemaTimeline(arg1:string):Promise<void>;

export function DeleteConnector(arg1:string):Promise<void>;

export function DeleteHook(arg1:string):Promise<void>;

export function DeleteMCPServer(arg1:string):Promise<void>;

export function DeleteMemoryItem(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteProvider(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function DeleteSnapshot(arg1:string):Promise<void>;

export function DiscoverProviderModels(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function EnqueueCinemaRender(arg1:string,arg2:string):Promise<cinema.RenderJob>;

export function ExportSettingsToFile():Promise<void>;

export function GetBrowserStatus():Promise<settingsops.BrowserStatus>;

export function GetComputerUseStatus():Promise<settingsops.ComputerUseStatus>;

export function GetGitStatus():Promise<settingsops.GitStatus>;

export function GetMCPServerStatus():Promise<mcp.LocalStatus>;

export function GetPreferences():Promise<store.Preferences>;

export function GetProjectEnvironment(arg1:string):Promise<settingsops.ProjectEnvironmentStatus>;

export function GetRuntimeEvents(arg1:string):Promise<Array<store.RuntimeEvent>>;

export function GetSession(arg1:string):Promise<store.Session>;

export function GetSettings():Promise<store.Settings>;

export function GetSkillDetail(arg1:string):Promise<skill.Skill>;

export function GetState():Promise<store.State>;

export function GitBranchList(arg1:string):Promise<string>;

export function GitLog(arg1:string,arg2:number):Promise<Array<git.LogEntry>>;

export function GitStatus(arg1:string):Promise<Array<git.FileStatus>>;

export function ImportSettingsFromFile():Promise<store.State>;

export function InstallMarketplacePlugin(arg1:string):Promise<store.PluginEntry>;

export function InstallPluginFromFolder():Promise<store.PluginEntry>;

export function InstallPluginFromURL(arg1:string):Promise<store.PluginEntry>;

export function InstallPluginFromZip():Promise<store.PluginEntry>;

export function InstallProviderFromCatalog(arg1:string):Promise<store.Provider>;

export function Interrupt():Promise<void>;

export function InterruptSession(arg1:string):Promise<void>;

export function IsRunning():Promise<boolean>;

export function IsSessionRunning(arg1:string):Promise<boolean>;

export function LSPCompletion(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<Array<string>>;

export function LSPDefinition(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<Array<lsp.Definition>>;

export function LSPDiagnosticsFor(arg1:string,arg2:string,arg3:string):Promise<Array<lsp.Diagnostic>>;

export function LSPStartServer(arg1:lsp.ServerConfig):Promise<void>;

export function LSPStopServer(arg1:string):Promise<void>;

export function ListAgentTools():Promise<Array<Record<string, string>>>;

export function ListArchivedSessions():Promise<Array<store.Session>>;

export function ListAudioInputDevices():Promise<Array<string>>;

export function ListAutomationRuns(arg1:string):Promise<Array<automation.Run>>;

export function ListAutomations():Promise<Array<automation.Definition>>;

export function ListBrowserTargets():Promise<Array<browser.Target>>;

export function ListCalendarEvents(arg1:number,arg2:number):Promise<Array<calendar.Event>>;

export function ListCinemaJobs():Promise<Array<cinema.RenderJob>>;

export function ListCinemaTimelines():Promise<Array<cinema.Timeline>>;

export function ListConnections():Promise<Array<store.SSHConnection>>;

export function ListConnectors():Promise<Array<connector.Definition>>;

export function ListDependencyChecks():Promise<Array<store.DependencyCheckResult>>;

export function ListFiles(arg1:string,arg2:string):Promise<Array<main.FileEntry>>;

export function ListHooks():Promise<Array<store.HookEntry>>;

export function ListMCPServers():Promise<Array<store.MCPServerEntry>>;

export function ListMemoryItems():Promise<Array<store.MemoryItem>>;

export function ListNotifications():Promise<Array<store.NotificationEvent>>;

export function ListPets():Promise<Array<store.Pet>>;

export function ListPluginEntries():Promise<Array<store.PluginEntry>>;

export function ListPluginsCatalog():Promise<Array<store.PluginEntry>>;

export function ListProjects():Promise<Array<store.Project>>;

export function ListProviderCatalog():Promise<Array<provider.CatalogItem>>;

export function ListProviders():Promise<Array<store.Provider>>;

export function ListPullRequests():Promise<Array<store.PullRequestItem>>;

export function ListScheduledTasks():Promise<Array<store.ScheduledTask>>;

export function ListSessions():Promise<Array<store.Session>>;

export function ListShortcuts():Promise<Array<store.ShortcutBinding>>;

export function ListSkills():Promise<Array<store.SkillEntry>>;

export function ListSnapshots(arg1:string):Promise<Array<store.SnapshotEntry>>;

export function NewSession(arg1:string):Promise<store.Session>;

export function NormalizeProviderURL(arg1:string,arg2:string):Promise<string>;

export function OnAgentEvent(arg1:any):Promise<void>;

export function OnAgentPlanMode(arg1:any):Promise<void>;

export function OnAgentQuestion(arg1:any):Promise<void>;

export function OnAgentRuntime(arg1:any):Promise<void>;

export function OpenManagedBrowser(arg1:string):Promise<void>;

export function OpenManagedBrowserDebug(arg1:string,arg2:number):Promise<void>;

export function OpenPath(arg1:string):Promise<void>;

export function OpenShell(arg1:string,arg2:string,arg3:string):Promise<void>;

export function PickAllowedApp():Promise<string>;

export function PickAttachmentFiles():Promise<Array<string>>;

export function PickDownloadsFolder():Promise<string>;

export function PickProjectFolder():Promise<store.Project>;

export function PickWorktreeRoot():Promise<string>;

export function ProbeProvider(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean,arg7:boolean,arg8:boolean):Promise<llm.ProbeResult>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadShell(arg1:string,arg2:number):Promise<string>;

export function RefreshMCPTools(arg1:string):Promise<store.MCPServerEntry>;

export function RefreshWorktrees(arg1:string):Promise<Array<store.WorktreeEntry>>;

export function RejectChanges(arg1:string,arg2:Array<string>):Promise<void>;

export function ReloadSkills():Promise<Array<store.SkillEntry>>;

export function RemoveSitePermission(arg1:string):Promise<Array<store.BrowserSitePermission>>;

export function ResizeShell(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResolveApproval(arg1:string,arg2:boolean):Promise<void>;

export function RestoreSnapshot(arg1:string):Promise<store.Session>;

export function RunAutomationNow(arg1:string):Promise<automation.Run>;

export function RunCodexTurn(arg1:string,arg2:string):Promise<void>;

export function RunScheduled(arg1:context.Context,arg2:store.ScheduledTask):Promise<void>;

export function RunScheduledTask(arg1:string):Promise<void>;

export function SaveAutomation(arg1:automation.Definition):Promise<automation.Definition>;

export function SaveCalendarEvent(arg1:calendar.Event):Promise<calendar.Event>;

export function SaveCinemaTimeline(arg1:cinema.Timeline):Promise<cinema.Timeline>;

export function SaveConnections(arg1:Array<store.SSHConnection>):Promise<void>;

export function SaveConnector(arg1:connector.Definition):Promise<connector.Definition>;

export function SaveHook(arg1:store.HookEntry):Promise<store.HookEntry>;

export function SaveMCPServer(arg1:store.MCPServerEntry):Promise<store.MCPServerEntry>;

export function SaveMemoryItem(arg1:store.MemoryItem):Promise<store.MemoryItem>;

export function SavePets(arg1:Array<store.Pet>):Promise<void>;

export function SavePluginEntries(arg1:Array<store.PluginEntry>):Promise<void>;

export function SavePreferences(arg1:store.Preferences):Promise<void>;

export function SaveProvider(arg1:store.Provider):Promise<void>;

export function SavePullRequests(arg1:Array<store.PullRequestItem>):Promise<void>;

export function SaveScheduledTasks(arg1:Array<store.ScheduledTask>):Promise<void>;

export function SaveSession(arg1:store.Session):Promise<void>;

export function SaveSettings(arg1:store.Settings):Promise<void>;

export function SaveShortcuts(arg1:Array<store.ShortcutBinding>):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function SendMessageWithAttachments(arg1:string,arg2:string,arg3:Array<agent.Attachment>):Promise<void>;

export function SendTestNotification():Promise<void>;

export function SetActiveProject(arg1:string):Promise<void>;

export function SetActiveSession(arg1:string):Promise<void>;

export function SetMCPServerEnabled(arg1:boolean):Promise<mcp.LocalStatus>;

export function SetPluginEnabled(arg1:string,arg2:boolean):Promise<store.PluginEntry>;

export function SetSkillEnabled(arg1:string,arg2:boolean):Promise<store.SkillEntry>;

export function TestConnector(arg1:string):Promise<connector.Definition>;

export function TestHook(arg1:store.HookEntry):Promise<store.HookEntry>;

export function TestMCPConnection(arg1:store.MCPServerEntry):Promise<store.MCPServerEntry>;

export function TestSSHConnection(arg1:string):Promise<store.SSHConnection>;

export function TuckPet():Promise<void>;

export function UnarchiveSession(arg1:string):Promise<void>;

export function UninstallPlugin(arg1:string):Promise<void>;

export function WakePet():Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;

export function WriteShell(arg1:string,arg2:string):Promise<void>;
