// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptChanges(arg1, arg2) {
  return window['go']['main']['App']['AcceptChanges'](arg1, arg2);
}

export function AddProject(arg1) {
  return window['go']['main']['App']['AddProject'](arg1);
}

export function AddSitePermission(arg1, arg2) {
  return window['go']['main']['App']['AddSitePermission'](arg1, arg2);
}

export function ArchiveSession(arg1) {
  return window['go']['main']['App']['ArchiveSession'](arg1);
}

export function BrowserEvaluate(arg1) {
  return window['go']['main']['App']['BrowserEvaluate'](arg1);
}

export function BrowserNavigate(arg1) {
  return window['go']['main']['App']['BrowserNavigate'](arg1);
}

export function BrowserScreenshot() {
  return window['go']['main']['App']['BrowserScreenshot']();
}

export function BrowserSnapshot() {
  return window['go']['main']['App']['BrowserSnapshot']();
}

export function BrowserVersion() {
  return window['go']['main']['App']['BrowserVersion']();
}

export function CancelCinemaJob(arg1) {
  return window['go']['main']['App']['CancelCinemaJob'](arg1);
}

export function CheckDependencies() {
  return window['go']['main']['App']['CheckDependencies']();
}

export function ClearBrowserData() {
  return window['go']['main']['App']['ClearBrowserData']();
}

export function CloseShell(arg1) {
  return window['go']['main']['App']['CloseShell'](arg1);
}

export function CommentOnHunk(arg1, arg2, arg3) {
  return window['go']['main']['App']['CommentOnHunk'](arg1, arg2, arg3);
}

export function CompactSession(arg1) {
  return window['go']['main']['App']['CompactSession'](arg1);
}

export function CreateCustomPet() {
  return window['go']['main']['App']['CreateCustomPet']();
}

export function CreateSnapshot(arg1, arg2) {
  return window['go']['main']['App']['CreateSnapshot'](arg1, arg2);
}

export function DeleteArchivedSession(arg1) {
  return window['go']['main']['App']['DeleteArchivedSession'](arg1);
}

export function DeleteArchivedSessions() {
  return window['go']['main']['App']['DeleteArchivedSessions']();
}

export function DeleteAutomation(arg1) {
  return window['go']['main']['App']['DeleteAutomation'](arg1);
}

export function DeleteCalendarEvent(arg1) {
  return window['go']['main']['App']['DeleteCalendarEvent'](arg1);
}

export function DeleteCinemaTimeline(arg1) {
  return window['go']['main']['App']['DeleteCinemaTimeline'](arg1);
}

export function DeleteConnector(arg1) {
  return window['go']['main']['App']['DeleteConnector'](arg1);
}

export function DeleteHook(arg1) {
  return window['go']['main']['App']['DeleteHook'](arg1);
}

export function DeleteMCPServer(arg1) {
  return window['go']['main']['App']['DeleteMCPServer'](arg1);
}

export function DeleteMemoryItem(arg1) {
  return window['go']['main']['App']['DeleteMemoryItem'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteProvider(arg1) {
  return window['go']['main']['App']['DeleteProvider'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DeleteSnapshot(arg1) {
  return window['go']['main']['App']['DeleteSnapshot'](arg1);
}

export function DiscoverProviderModels(arg1, arg2, arg3) {
  return window['go']['main']['App']['DiscoverProviderModels'](arg1, arg2, arg3);
}

export function EnqueueCinemaRender(arg1, arg2) {
  return window['go']['main']['App']['EnqueueCinemaRender'](arg1, arg2);
}

export function ExportSettingsToFile() {
  return window['go']['main']['App']['ExportSettingsToFile']();
}

export function GetBrowserStatus() {
  return window['go']['main']['App']['GetBrowserStatus']();
}

export function GetComputerUseStatus() {
  return window['go']['main']['App']['GetComputerUseStatus']();
}

export function GetGitStatus() {
  return window['go']['main']['App']['GetGitStatus']();
}

export function GetMCPServerStatus() {
  return window['go']['main']['App']['GetMCPServerStatus']();
}

export function GetPreferences() {
  return window['go']['main']['App']['GetPreferences']();
}

export function GetProjectEnvironment(arg1) {
  return window['go']['main']['App']['GetProjectEnvironment'](arg1);
}

export function GetRuntimeEvents(arg1) {
  return window['go']['main']['App']['GetRuntimeEvents'](arg1);
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSkillDetail(arg1) {
  return window['go']['main']['App']['GetSkillDetail'](arg1);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GitBranchList(arg1) {
  return window['go']['main']['App']['GitBranchList'](arg1);
}

export function GitLog(arg1, arg2) {
  return window['go']['main']['App']['GitLog'](arg1, arg2);
}

export function GitStatus(arg1) {
  return window['go']['main']['App']['GitStatus'](arg1);
}

export function ImportSettingsFromFile() {
  return window['go']['main']['App']['ImportSettingsFromFile']();
}

export function InstallMarketplacePlugin(arg1) {
  return window['go']['main']['App']['InstallMarketplacePlugin'](arg1);
}

export function InstallPluginFromFolder() {
  return window['go']['main']['App']['InstallPluginFromFolder']();
}

export function InstallPluginFromURL(arg1) {
  return window['go']['main']['App']['InstallPluginFromURL'](arg1);
}

export function InstallPluginFromZip() {
  return window['go']['main']['App']['InstallPluginFromZip']();
}

export function InstallProviderFromCatalog(arg1) {
  return window['go']['main']['App']['InstallProviderFromCatalog'](arg1);
}

export function Interrupt() {
  return window['go']['main']['App']['Interrupt']();
}

export function InterruptSession(arg1) {
  return window['go']['main']['App']['InterruptSession'](arg1);
}

export function IsRunning() {
  return window['go']['main']['App']['IsRunning']();
}

export function IsSessionRunning(arg1) {
  return window['go']['main']['App']['IsSessionRunning'](arg1);
}

export function LSPCompletion(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['LSPCompletion'](arg1, arg2, arg3, arg4, arg5);
}

export function LSPDefinition(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['LSPDefinition'](arg1, arg2, arg3, arg4, arg5);
}

export function LSPDiagnosticsFor(arg1, arg2, arg3) {
  return window['go']['main']['App']['LSPDiagnosticsFor'](arg1, arg2, arg3);
}

export function LSPStartServer(arg1) {
  return window['go']['main']['App']['LSPStartServer'](arg1);
}

export function LSPStopServer(arg1) {
  return window['go']['main']['App']['LSPStopServer'](arg1);
}

export function ListAgentTools() {
  return window['go']['main']['App']['ListAgentTools']();
}

export function ListArchivedSessions() {
  return window['go']['main']['App']['ListArchivedSessions']();
}

export function ListAudioInputDevices() {
  return window['go']['main']['App']['ListAudioInputDevices']();
}

export function ListAutomationRuns(arg1) {
  return window['go']['main']['App']['ListAutomationRuns'](arg1);
}

export function ListAutomations() {
  return window['go']['main']['App']['ListAutomations']();
}

export function ListBrowserTargets() {
  return window['go']['main']['App']['ListBrowserTargets']();
}

export function ListCalendarEvents(arg1, arg2) {
  return window['go']['main']['App']['ListCalendarEvents'](arg1, arg2);
}

export function ListCinemaJobs() {
  return window['go']['main']['App']['ListCinemaJobs']();
}

export function ListCinemaTimelines() {
  return window['go']['main']['App']['ListCinemaTimelines']();
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function ListConnectors() {
  return window['go']['main']['App']['ListConnectors']();
}

export function ListDependencyChecks() {
  return window['go']['main']['App']['ListDependencyChecks']();
}

export function ListFiles(arg1, arg2) {
  return window['go']['main']['App']['ListFiles'](arg1, arg2);
}

export function ListHooks() {
  return window['go']['main']['App']['ListHooks']();
}

export function ListMCPServers() {
  return window['go']['main']['App']['ListMCPServers']();
}

export function ListMemoryItems() {
  return window['go']['main']['App']['ListMemoryItems']();
}

export function ListNotifications() {
  return window['go']['main']['App']['ListNotifications']();
}

export function ListPets() {
  return window['go']['main']['App']['ListPets']();
}

export function ListPluginEntries() {
  return window['go']['main']['App']['ListPluginEntries']();
}

export function ListPluginsCatalog() {
  return window['go']['main']['App']['ListPluginsCatalog']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListProviderCatalog() {
  return window['go']['main']['App']['ListProviderCatalog']();
}

export function ListProviders() {
  return window['go']['main']['App']['ListProviders']();
}

export function ListPullRequests() {
  return window['go']['main']['App']['ListPullRequests']();
}

export function ListScheduledTasks() {
  return window['go']['main']['App']['ListScheduledTasks']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListShortcuts() {
  return window['go']['main']['App']['ListShortcuts']();
}

export function ListSkills() {
  return window['go']['main']['App']['ListSkills']();
}

export function ListSnapshots(arg1) {
  return window['go']['main']['App']['ListSnapshots'](arg1);
}

export function NewSession(arg1) {
  return window['go']['main']['App']['NewSession'](arg1);
}

export function NormalizeProviderURL(arg1, arg2) {
  return window['go']['main']['App']['NormalizeProviderURL'](arg1, arg2);
}

export function OnAgentEvent(arg1) {
  return window['go']['main']['App']['OnAgentEvent'](arg1);
}

export function OnAgentPlanMode(arg1) {
  return window['go']['main']['App']['OnAgentPlanMode'](arg1);
}

export function OnAgentQuestion(arg1) {
  return window['go']['main']['App']['OnAgentQuestion'](arg1);
}

export function OnAgentRuntime(arg1) {
  return window['go']['main']['App']['OnAgentRuntime'](arg1);
}

export function OpenManagedBrowser(arg1) {
  return window['go']['main']['App']['OpenManagedBrowser'](arg1);
}

export function OpenManagedBrowserDebug(arg1, arg2) {
  return window['go']['main']['App']['OpenManagedBrowserDebug'](arg1, arg2);
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function OpenShell(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenShell'](arg1, arg2, arg3);
}

export function PickAllowedApp() {
  return window['go']['main']['App']['PickAllowedApp']();
}

export function PickAttachmentFiles() {
  return window['go']['main']['App']['PickAttachmentFiles']();
}

export function PickDownloadsFolder() {
  return window['go']['main']['App']['PickDownloadsFolder']();
}

export function PickProjectFolder() {
  return window['go']['main']['App']['PickProjectFolder']();
}

export function PickWorktreeRoot() {
  return window['go']['main']['App']['PickWorktreeRoot']();
}

export function ProbeProvider(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['ProbeProvider'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadShell(arg1, arg2) {
  return window['go']['main']['App']['ReadShell'](arg1, arg2);
}

export function RefreshMCPTools(arg1) {
  return window['go']['main']['App']['RefreshMCPTools'](arg1);
}

export function RefreshWorktrees(arg1) {
  return window['go']['main']['App']['RefreshWorktrees'](arg1);
}

export function RejectChanges(arg1, arg2) {
  return window['go']['main']['App']['RejectChanges'](arg1, arg2);
}

export function ReloadSkills() {
  return window['go']['main']['App']['ReloadSkills']();
}

export function RemoveSitePermission(arg1) {
  return window['go']['main']['App']['RemoveSitePermission'](arg1);
}

export function ResizeShell(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeShell'](arg1, arg2, arg3);
}

export function ResolveApproval(arg1, arg2) {
  return window['go']['main']['App']['ResolveApproval'](arg1, arg2);
}

export function RestoreSnapshot(arg1) {
  return window['go']['main']['App']['RestoreSnapshot'](arg1);
}

export function RunAutomationNow(arg1) {
  return window['go']['main']['App']['RunAutomationNow'](arg1);
}

export function RunCodexTurn(arg1, arg2) {
  return window['go']['main']['App']['RunCodexTurn'](arg1, arg2);
}

export function RunScheduled(arg1, arg2) {
  return window['go']['main']['App']['RunScheduled'](arg1, arg2);
}

export function RunScheduledTask(arg1) {
  return window['go']['main']['App']['RunScheduledTask'](arg1);
}

export function SaveAutomation(arg1) {
  return window['go']['main']['App']['SaveAutomation'](arg1);
}

export function SaveCalendarEvent(arg1) {
  return window['go']['main']['App']['SaveCalendarEvent'](arg1);
}

export function SaveCinemaTimeline(arg1) {
  return window['go']['main']['App']['SaveCinemaTimeline'](arg1);
}

export function SaveConnections(arg1) {
  return window['go']['main']['App']['SaveConnections'](arg1);
}

export function SaveConnector(arg1) {
  return window['go']['main']['App']['SaveConnector'](arg1);
}

export function SaveHook(arg1) {
  return window['go']['main']['App']['SaveHook'](arg1);
}

export function SaveMCPServer(arg1) {
  return window['go']['main']['App']['SaveMCPServer'](arg1);
}

export function SaveMemoryItem(arg1) {
  return window['go']['main']['App']['SaveMemoryItem'](arg1);
}

export function SavePets(arg1) {
  return window['go']['main']['App']['SavePets'](arg1);
}

export function SavePluginEntries(arg1) {
  return window['go']['main']['App']['SavePluginEntries'](arg1);
}

export function SavePreferences(arg1) {
  return window['go']['main']['App']['SavePreferences'](arg1);
}

export function SaveProvider(arg1) {
  return window['go']['main']['App']['SaveProvider'](arg1);
}

export function SavePullRequests(arg1) {
  return window['go']['main']['App']['SavePullRequests'](arg1);
}

export function SaveScheduledTasks(arg1) {
  return window['go']['main']['App']['SaveScheduledTasks'](arg1);
}

export function SaveSession(arg1) {
  return window['go']['main']['App']['SaveSession'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveShortcuts(arg1) {
  return window['go']['main']['App']['SaveShortcuts'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SendMessageWithAttachments(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessageWithAttachments'](arg1, arg2, arg3);
}

export function SendTestNotification() {
  return window['go']['main']['App']['SendTestNotification']();
}

export function SetActiveProject(arg1) {
  return window['go']['main']['App']['SetActiveProject'](arg1);
}

export function SetActiveSession(arg1) {
  return window['go']['main']['App']['SetActiveSession'](arg1);
}

export function SetMCPServerEnabled(arg1) {
  return window['go']['main']['App']['SetMCPServerEnabled'](arg1);
}

export function SetPluginEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetPluginEnabled'](arg1, arg2);
}

export function SetSkillEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetSkillEnabled'](arg1, arg2);
}

export function TestConnector(arg1) {
  return window['go']['main']['App']['TestConnector'](arg1);
}

export function TestHook(arg1) {
  return window['go']['main']['App']['TestHook'](arg1);
}

export function TestMCPConnection(arg1) {
  return window['go']['main']['App']['TestMCPConnection'](arg1);
}

export function TestSSHConnection(arg1) {
  return window['go']['main']['App']['TestSSHConnection'](arg1);
}

export function TuckPet() {
  return window['go']['main']['App']['TuckPet']();
}

export function UnarchiveSession(arg1) {
  return window['go']['main']['App']['UnarchiveSession'](arg1);
}

export function UninstallPlugin(arg1) {
  return window['go']['main']['App']['UninstallPlugin'](arg1);
}

export function WakePet() {
  return window['go']['main']['App']['WakePet']();
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}

export function WriteShell(arg1, arg2) {
  return window['go']['main']['App']['WriteShell'](arg1, arg2);
}
