"""Generate the TypeScript protocol layer from the extracted protocol.json.

Everything the React frontend knows about the wire protocol comes from here.
Nothing is hand-written, so coverage cannot silently drift from the server.
"""

import io
import json
import os

SRC = "frontend/src/protocol/generated/protocol.json"
OUT = "frontend/src/protocol"

data = json.load(io.open(SRC, encoding="utf-8"))
notifications = data["notifications"]
requests = data["requests"]
block_types = data["blockTypes"]
statuses = data["statuses"]
phases = data["phases"]

BANNER = """// AUTO-GENERATED by scripts/gen-protocol-ts.py — DO NOT EDIT BY HAND.
//
// Source of truth: src/backend/app-server-protocol/src/protocol/common.rs
//                  (server_notification_definitions! / server_request_definitions!)
//                  codex-asar-extract/webview/assets/conversation-blocks-*.js
//
// Regenerate with:  python scripts/gen-protocol.py && python scripts/gen-protocol-ts.py
"""

os.makedirs(OUT, exist_ok=True)

# ── notifications.ts ──────────────────────────────────────────────────
lines = [BANNER, ""]
lines.append("/** Every notification method app-server can push to a client. */")
lines.append("export const NOTIFICATION_METHODS = [")
for n in notifications:
    lines.append('  "%s",' % n["method"])
lines.append("] as const;")
lines.append("")
lines.append("export type NotificationMethod = (typeof NOTIFICATION_METHODS)[number];")
lines.append("")
lines.append("/** Methods gated behind `capabilities.experimentalApi = true`. */")
lines.append("export const EXPERIMENTAL_NOTIFICATION_METHODS = [")
for n in notifications:
    if n["experimental"]:
        lines.append('  "%s",' % n["method"])
lines.append("] as const;")
lines.append("")
lines.append("export type ExperimentalNotificationMethod =")
lines.append("  (typeof EXPERIMENTAL_NOTIFICATION_METHODS)[number];")
lines.append("")
lines.append("/** method -> Rust variant name, for tracing back to the server source. */")
lines.append("export const NOTIFICATION_VARIANTS: Record<NotificationMethod, string> = {")
for n in notifications:
    lines.append('  "%s": "%s",' % (n["method"], n["variant"]))
lines.append("};")
lines.append("")
lines.append("const NOTIFICATION_SET: ReadonlySet<string> = new Set(NOTIFICATION_METHODS);")
lines.append("")
lines.append("/** Narrow an arbitrary wire string to a known notification method. */")
lines.append("export function isNotificationMethod(method: string): method is NotificationMethod {")
lines.append("  return NOTIFICATION_SET.has(method);")
lines.append("}")
lines.append("")

with io.open(os.path.join(OUT, "notifications.ts"), "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines))

# ── requests.ts ───────────────────────────────────────────────────────
lines = [BANNER, ""]
lines.append("/** Server -> client requests (approvals, user input, elicitation, …). */")
lines.append("export const SERVER_REQUEST_METHODS = [")
for r in requests:
    lines.append('  "%s",' % r["method"])
lines.append("] as const;")
lines.append("")
lines.append("export type ServerRequestMethod = (typeof SERVER_REQUEST_METHODS)[number];")
lines.append("")
lines.append("export const SERVER_REQUEST_VARIANTS: Record<ServerRequestMethod, string> = {")
for r in requests:
    lines.append('  "%s": "%s",' % (r["method"], r["variant"]))
lines.append("};")
lines.append("")
lines.append("/** Requests that must be answered with an approval decision. */")
lines.append("export const APPROVAL_REQUEST_METHODS = [")
for r in requests:
    if "Approval" in r["method"]:
        lines.append('  "%s",' % r["method"])
lines.append("] as const;")
lines.append("")
lines.append("/** Requests that ask the user a free-form question. */")
lines.append("export const USER_INPUT_REQUEST_METHODS = [")
for r in requests:
    if "requestUserInput" in r["method"] or "elicitation" in r["method"]:
        lines.append('  "%s",' % r["method"])
lines.append("] as const;")
lines.append("")

with io.open(os.path.join(OUT, "requests.ts"), "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines))

# ── blocks.ts ─────────────────────────────────────────────────────────
lines = [BANNER, ""]
lines.append("/** Item tags the official turn stream renders as distinct blocks. */")
lines.append("export const BLOCK_TYPES = [")
for b in block_types:
    lines.append('  "%s",' % b)
lines.append("] as const;")
lines.append("")
lines.append("export type BlockType = (typeof BLOCK_TYPES)[number];")
lines.append("")
lines.append("/** Blocks that represent a tool/command invocation with a lifecycle. */")
lines.append("export const TOOL_BLOCK_TYPES: readonly BlockType[] = [")
for b in ["commandExecution", "exec", "patch", "fileChange", "mcp-tool-call", "mcpToolCall", "dynamic-tool-call", "dynamicToolCall", "search", "read", "list_files"]:
    if b in block_types:
        lines.append('  "%s",' % b)
lines.append("];")
lines.append("")
lines.append("/** Blocks that carry streamed assistant prose. */")
lines.append("export const TEXT_BLOCK_TYPES: readonly BlockType[] = [")
for b in ["agentMessage", "assistant-message", "user-message", "reasoning", "realtime-transcript"]:
    if b in block_types:
        lines.append('  "%s",' % b)
lines.append("];")
lines.append("")
lines.append("/** Blocks that represent a plan the user can review. */")
lines.append("export const PLAN_BLOCK_TYPES: readonly BlockType[] = [")
for b in ["plan", "proposed-plan"]:
    if b in block_types:
        lines.append('  "%s",' % b)
lines.append("];")
lines.append("")

with io.open(os.path.join(OUT, "blocks.ts"), "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines))

# ── status.ts ─────────────────────────────────────────────────────────
lines = [BANNER, ""]
lines.append("/** The official item/turn status vocabulary. */")
lines.append("export const ITEM_STATUSES = [")
for s in statuses:
    lines.append('  "%s",' % s)
lines.append("] as const;")
lines.append("")
lines.append("export type ItemStatus = (typeof ITEM_STATUSES)[number];")
lines.append("")
lines.append("/** Statuses that mean the item is still working. */")
lines.append("export const ACTIVE_STATUSES: readonly ItemStatus[] = [")
for s in ["running", "inProgress", "in_progress"]:
    if s in statuses:
        lines.append('  "%s",' % s)
lines.append("];")
lines.append("")
lines.append("/** Statuses that mean the item finished without a successful result. */")
lines.append("export const FAILURE_STATUSES: readonly ItemStatus[] = [")
for s in ["failed", "denied", "interrupted", "skipped"]:
    if s in statuses:
        lines.append('  "%s",' % s)
lines.append("];")
lines.append("")
lines.append("/** Turn phases the server reports on agent messages. */")
lines.append("export const TURN_PHASES = [")
for p in sorted(set(phases) | {"commentary", "final_answer"}):
    lines.append('  "%s",' % p)
lines.append("] as const;")
lines.append("")
lines.append("export type TurnPhase = (typeof TURN_PHASES)[number];")
lines.append("")

with io.open(os.path.join(OUT, "status.ts"), "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines))

print("wrote:")
for name in ("notifications.ts", "requests.ts", "blocks.ts", "status.ts"):
    p = os.path.join(OUT, name)
    print("  %-20s %d bytes" % (name, os.path.getsize(p)))
