// AUTO-GENERATED by scripts/gen-protocol-ts.py — DO NOT EDIT BY HAND.
//
// Source of truth: src/backend/app-server-protocol/src/protocol/common.rs
//                  (server_notification_definitions! / server_request_definitions!)
//                  codex-asar-extract/webview/assets/conversation-blocks-*.js
//
// Regenerate with:  python scripts/gen-protocol.py && python scripts/gen-protocol-ts.py


/** Item tags the official turn stream renders as distinct blocks. */
export const BLOCK_TYPES = [
  "add",
  "agentMessage",
  "assistant-message",
  "automatic-approval-review",
  "code",
  "codespan",
  "codexDirective",
  "commandExecution",
  "context-compaction",
  "delete",
  "dynamic-tool-call",
  "dynamicToolCall",
  "error",
  "exec",
  "file",
  "fileChange",
  "generated-image",
  "google-drive",
  "heartbeat",
  "imageGeneration",
  "install",
  "list_files",
  "mcp-tool-call",
  "mcpToolCall",
  "paragraph",
  "patch",
  "plan",
  "plugin",
  "proposed-plan",
  "read",
  "realtime-transcript",
  "reasoning",
  "search",
  "subagent-activity",
  "success",
  "system-error",
  "unknown",
  "update",
  "url",
  "user-message",
  "worked-for",
] as const;

export type BlockType = (typeof BLOCK_TYPES)[number];

/** Blocks that represent a tool/command invocation with a lifecycle. */
export const TOOL_BLOCK_TYPES: readonly BlockType[] = [
  "commandExecution",
  "exec",
  "patch",
  "fileChange",
  "mcp-tool-call",
  "mcpToolCall",
  "dynamic-tool-call",
  "dynamicToolCall",
  "search",
  "read",
  "list_files",
];

/** Blocks that carry streamed assistant prose. */
export const TEXT_BLOCK_TYPES: readonly BlockType[] = [
  "agentMessage",
  "assistant-message",
  "user-message",
  "reasoning",
  "realtime-transcript",
];

/** Blocks that represent a plan the user can review. */
export const PLAN_BLOCK_TYPES: readonly BlockType[] = [
  "plan",
  "proposed-plan",
];
