// AUTO-GENERATED by scripts/gen-protocol-ts.py 鈥?DO NOT EDIT BY HAND.
//
// Source of truth: frozen protocol snapshot (backend removed)
//                  (server_notification_definitions! / server_request_definitions!)
//                  codex-asar-extract/webview/assets/conversation-blocks-*.js
//
// Regenerate with:  python scripts/gen-protocol.py && python scripts/gen-protocol-ts.py


/** Server -> client requests (approvals, user input, elicitation, 鈥?. */
export const SERVER_REQUEST_METHODS = [
  "item/commandExecution/requestApproval",
  "item/fileChange/requestApproval",
  "item/tool/requestUserInput",
  "mcpServer/elicitation/request",
  "item/permissions/requestApproval",
  "item/tool/call",
  "account/chatgptAuthTokens/refresh",
  "attestation/generate",
  "currentTime/read",
] as const;

export type ServerRequestMethod = (typeof SERVER_REQUEST_METHODS)[number];

export const SERVER_REQUEST_VARIANTS: Record<ServerRequestMethod, string> = {
  "item/commandExecution/requestApproval": "CommandExecutionRequestApproval",
  "item/fileChange/requestApproval": "FileChangeRequestApproval",
  "item/tool/requestUserInput": "ToolRequestUserInput",
  "mcpServer/elicitation/request": "McpServerElicitationRequest",
  "item/permissions/requestApproval": "PermissionsRequestApproval",
  "item/tool/call": "DynamicToolCall",
  "account/chatgptAuthTokens/refresh": "ChatgptAuthTokensRefresh",
  "attestation/generate": "AttestationGenerate",
  "currentTime/read": "CurrentTimeRead",
};

/** Requests that must be answered with an approval decision. */
export const APPROVAL_REQUEST_METHODS = [
  "item/commandExecution/requestApproval",
  "item/fileChange/requestApproval",
  "item/permissions/requestApproval",
] as const;

/** Requests that ask the user a free-form question. */
export const USER_INPUT_REQUEST_METHODS = [
  "item/tool/requestUserInput",
  "mcpServer/elicitation/request",
] as const;

