// AUTO-GENERATED by scripts/gen-protocol-ts.py 鈥?DO NOT EDIT BY HAND.
//
// Source of truth: frozen protocol snapshot (backend removed)
//                  (server_notification_definitions! / server_request_definitions!)
//                  codex-asar-extract/webview/assets/conversation-blocks-*.js
//
// Regenerate with:  python scripts/gen-protocol.py && python scripts/gen-protocol-ts.py


/** The official item/turn status vocabulary. */
export const ITEM_STATUSES = [
  "completed",
  "denied",
  "done",
  "failed",
  "inProgress",
  "in_progress",
  "interrupted",
  "running",
  "skipped",
] as const;

export type ItemStatus = (typeof ITEM_STATUSES)[number];

/** Statuses that mean the item is still working. */
export const ACTIVE_STATUSES: readonly ItemStatus[] = [
  "running",
  "inProgress",
  "in_progress",
];

/** Statuses that mean the item finished without a successful result. */
export const FAILURE_STATUSES: readonly ItemStatus[] = [
  "failed",
  "denied",
  "interrupted",
  "skipped",
];

/** Turn phases the server reports on agent messages. */
export const TURN_PHASES = [
  "commentary",
  "final_answer",
] as const;

export type TurnPhase = (typeof TURN_PHASES)[number];

